2019-12-22 22:15:01,040 ERROR: Exception on /reset_password_request [GET] [in /Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/enriquegoudet/Documents/ProjectDope/app/routes.py", line 152, in reset_password_request
    form = ResetPasswordRequestForm()
NameError: name 'ResetPasswordRequestForm' is not defined
2019-12-22 22:15:50,963 INFO: Microblog startup [in /Users/enriquegoudet/Documents/ProjectDope/app/__init__.py:47]
2019-12-22 22:16:07,742 INFO: Microblog startup [in /Users/enriquegoudet/Documents/ProjectDope/app/__init__.py:47]
2019-12-22 22:16:32,426 ERROR: Exception on /reset_password_request [POST] [in /Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/enriquegoudet/Documents/ProjectDope/app/routes.py", line 154, in reset_password_request
    user = User.query.filter_by(email=user.email.data).first()
UnboundLocalError: local variable 'user' referenced before assignment
2019-12-22 22:17:28,850 INFO: Microblog startup [in /Users/enriquegoudet/Documents/ProjectDope/app/__init__.py:47]
2019-12-22 22:19:08,817 ERROR: Exception on /reset_password_request [POST] [in /Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/enriquegoudet/Documents/ProjectDope/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/enriquegoudet/Documents/ProjectDope/app/routes.py", line 154, in reset_password_request
    user = User.query.filter_by(email=user.email.data).first()
UnboundLocalError: local variable 'user' referenced before assignment
2019-12-25 16:55:15,583 INFO: Microblog startup [in /Users/enriquegoudet/Documents/ProjectDope/app/__init__.py:49]
2019-12-25 17:02:53,482 INFO: Microblog startup [in /Users/enriquegoudet/Documents/ProjectDope/app/__init__.py:49]
